In [ ]:
NUMPY TUTORIAL

In [ ]:
It is a  package for scientific computing with python

In [ ]:
It consists of High performance MultiDimensional Array object

In [ ]:
CREATING ARRAY OF OBJECT(2,3) I.E (2 rows and 3 column)

In [1]:
import numpy as np

In [3]:
print("printing 2 dimensional array")
arr1 = np.array([[1,2,3],[4,5,6]])
print("arr1", arr1)

arr1 [[1 2 3]
 [4 5 6]]


In [ ]:
CREATING NUMPY ARRAY OF OBJECT(3,4)(from list).. I.E (3 rows and 4 column)

In [5]:
arr2 = np.array([[5,6,7,8],[1,2,3,4],[6,6,6,6]])
print("arr2: ", arr2)


arr2:  [[5 6 7 8]
 [1 2 3 4]
 [6 6 6 6]]


In [7]:
arr3 = np.array([1,2,'b',9.0])
print("arr3: ", arr3)
print("type(arr3)", type(arr3))

arr3:  ['1' '2' 'b' '9.0']
type(arr3) <class 'numpy.ndarray'>


In [ ]:
CREATING ARRAY OF SHAPE(3,2)

In [8]:
arr4 = np.array([[2,3],[7,7],['n','j']])
print("arr4: ", arr4)
print()

arr4:  [['2' '3']
 ['7' '7']
 ['n' 'j']]


In [ ]:
DIMENSION ,SHAPE AND SIZE OF ARRAY

In [17]:
# CREATING ARRAY OF OBJECT(3,4)

arr2 = np.array([[5,6,7,8],[1,2,3,4],[6,6,6,6]])
print("arr2: ", arr2)
print()

print("No of Dimension:", arr.ndim )
print("No of Dimension:", arr4.ndim)
print("No of Dimension: ", arr3.ndim)
print("no of Dimension: ", arr4.ndim)
print()
print("SHAPES OF ARRAY")
print("shape of arr1: ", arr1.shape)
print("shape of arr2: ", arr2.shape)
print("shape of arr3: ", arr3.shape)
print("shape of arr4: ", arr4.shape)
print()
print("SIZE OF ARRAY")
print("size of arr1", arr1.size)
print("size of arr2: ", arr2.size)
print("size of arr3:", arr3.size)
print("size of arr4: ", arr4.size)


arr2:  [[5 6 7 8]
 [1 2 3 4]
 [6 6 6 6]]

No of Dimension: 2
No of Dimension: 2
No of Dimension:  1
no of Dimension:  2

SHAPES OF ARRAY
shape of arr1:  (2, 3)
shape of arr2:  (3, 4)
shape of arr3:  (4,)
shape of arr4:  (3, 2)

SIZE OF ARRAY
size of arr1 6
size of arr2:  12
size of arr3: 4
size of arr4:  6


In [ ]:
DTYPE()

In [19]:
print("arr1.dtype: ", arr1.dtype)
print("arr2.dtype: ", arr2.dtype)
print("arr3.dtype: ", arr3.dtype)
print("arr4.dtype: ", arr4.dtype)

arr1.dtype:  int32
arr2.dtype:  int32
arr3.dtype:  <U11
arr4.dtype:  <U11


In [ ]:
CREATING NUMPY ARRAY FROM LIST(BY PASSING LIST)

In [24]:
a = np.array([[2,3,'h'],[5,6,7],[9,5.6,2.3],[1,9,0],['e','q','s']])
print("numpy of array: ", a)
print()
print("shape_of_array: ", a.shape)
print("size_of_array: ", a.size)
print("a.ndim: ", a.ndim)
print('a.dtype: ', a.dtype)

numpy of array:  [['2' '3' 'h']
 ['5' '6' '7']
 ['9' '5.6' '2.3']
 ['1' '9' '0']
 ['e' 'q' 's']]

shape_of_array:  (5, 3)
size_of_array:  15
a.ndim:  2
a.dtype:  <U11


In [28]:
# CREATIMG NUMPY ARRAY BY PASING LIST OF SIZE(4,3)
a1 = np.array([[20,21,23],[24,25,27],[67,68,69],[11,12,13]], dtype='float')
print("a1: ", a1)
print("a1.dtype: ", a1.dtype)
print("shape_of_a1: ", a1.shape)

a1:  [[20. 21. 23.]
 [24. 25. 27.]
 [67. 68. 69.]
 [11. 12. 13.]]
a1.dtype:  float64
shape_of_a1:  (4, 3)


In [ ]:
CREATING NUMPY ARRAY FROM TUPLE

In [38]:
a3 =np.array(((90,45,67),(12,13,14),(34,45,55)))
print("numpy_array_of_tuple: ", a3)
print("shape_of_a3: ", a3.shape)
print("a3.size: ", a3.size)
print("a3.ndim: ", a3.ndim)
print("a3.dtype: ", a3.dtype)
print()
t = (3,4,'r',8.9)
a4 = np.array(t)
print("a4: ", a4)
print("a4.type: ", type(a4))
print()
t1 = ((2,3),(9,0),(4,5))
a5 = np.array(t1)
print("a5: ", a5)
print("type(a5): ", type(a5))
print()
a6 = np.array((9,4,5))
print("a6: ", a6)

numpy_array_of_tuple:  [[90 45 67]
 [12 13 14]
 [34 45 55]]
shape_of_a3:  (3, 3)
a3.size:  9
a3.ndim:  2
a3.dtype:  int32

a4:  ['3' '4' 'r' '8.9']
a4.type:  <class 'numpy.ndarray'>

a5:  [[2 3]
 [9 0]
 [4 5]]
type(a5):  <class 'numpy.ndarray'>

a6:  [9 4 5]


In [ ]:
Creating Numpy array of shape(3,2) of all zeros

In [41]:
x = np.zeros((3,2))
print("x: ", x)
print("x.dtype: ", x.dtype)
print()
x1 = np.zeros((3,4))
print("x1: ", x1)
print("x1.shape: ", x1.shape)

x:  [[0. 0.]
 [0. 0.]
 [0. 0.]]
x.dtype:  float64

x1:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
x1.shape:  (3, 4)


In [ ]:
Creating Numpy array of shape(4,3) of all one

In [42]:
x2 = np.ones((4,3))
print("x2: ", x2)

x2:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [1]:
# Creating Numpy of shape (3,3) and value of 24 and type =float
import numpy as np
j  = np.full((3,3),24, dtype='float')
print("j: ", j)
print()
j1 = np.full((2,5),30,dtype='float')
print("j1: ", j1)
print()
j2 = np.full((2,4),40)
print("j2: ", j2)

j:  [[24. 24. 24.]
 [24. 24. 24.]
 [24. 24. 24.]]

j1:  [[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]

j2:  [[40 40 40 40]
 [40 40 40 40]]


In [ ]:
CREATING NUMPY ARRAY OF SHAPE(4,1) AND VALUE OF 12 AND DATATYPE COMPLEX NUMBER

In [ ]:
CREATING ARRAY WITH RANDOM VALUES OF ANY SHAPE

In [5]:
import numpy as np
e = np.random.random((2,5))
print("e: ", e)
print()
import random
x = np.random.randint(1,8,20)
print("x:", x)

e:  [[0.4882516  0.76271753 0.48685305 0.8456727  0.85421998]
 [0.83618576 0.47039279 0.09480274 0.58014886 0.03051079]]

x: [5 7 5 3 4 3 4 2 7 1 2 6 3 7 5 4 4 1 6 2]


In [4]:
CREATING NUMPY ARRAY OF VALUE 1 TO 40 WITH A GAP OF 4

SyntaxError: invalid syntax (<ipython-input-4-79455d67127b>, line 1)

In [15]:
x3 = np.arange(1,40,4)
print("x:", x3)
print("type(x3):", type(x3))
print()

# Creating Numpy array of value from 1 to 25 with gap of 5
x4 = np.arange(1,25,5)
print("x4:", x4)

print()
# Create a numpy array sequence of integers from 10 to 1 with a step of -2
x5 = np.arange(10,1,-2)
print("x5:",x5)


x: [ 1  5  9 13 17 21 25 29 33 37]
type(x3): <class 'numpy.ndarray'>

x4: [ 1  6 11 16 21]

x5: [10  8  6  4  2]


In [ ]:
SLICING NUMPY ARRAY

In [ ]:
# NOW we get numpy array(z1) and now from  this array,we want some
 # random value from z1 in z2,and we get those value in z2 by providing index number of those value which is in z1

In [ ]:
NOW  CREATING NEW NUMPY ARRAY(Z1) FROM SOME RANGE AND THEN CREATE ANOTHER NUMPY ARRAY(Z2)
WHICH CONTAINS SOME VALUES FROM (Z1), WHICH WE GET, BY PROVING INDEX NUMBER OF THOSE VALUE WHICH ARE IN (Z1)

In [28]:
z1 = np.arange(12,1,-2)
print("z1:", z1)
print()
z2 = z1[np.array([0,0,4,4])]
print("z2: ", z2)
print()
z3 = z1[np.array([0,2,1,0])]
print("z3: ", z3)
print()
z4 = z1[np.array([0,0,0,1])]
print("z4:", z4)
print()
j = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
print("j:", j)
j2 = j[np.array([0,2,4,6])]
print("j2:", j2)
print()
j3 = j[np.array([0,6,6,0])]
print("j3:", j3)

z1: [12 10  8  6  4  2]

z2:  [12 12  4  4]

z3:  [12  8 10 12]

z4: [12 12 12 10]

j: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
j2: [1 3 5 7]

j3: [1 7 7 1]


In [ ]:
CREATING NUMPY ARRAY OF VALUE 20

In [45]:
nn = np.arange(21)
print("nn:", nn)
print()
nn1 = nn[np.array([0,6,11,12])]
print("nn1:", nn1)
print()
nn2 = nn[2:9]
print("nn2:", nn2)
print()
nn3=  nn[0:6]
print("nn3:", nn3)
print()
nn4 = nn[0:10:3]
print("nn4: ", nn4)
print()
nn5 = nn[3:10:4]
print("nn5 :", nn5)
print()
nn6 = nn[14:3:-3]
print("nn6:", nn6)
print()
nn7 = nn[6:]
print("nn7: ", nn7)
print()
nn8 = nn[:5]
print("nn8: ", nn8)
print()
nn9 = nn[4::3]
print("nn9:", nn9)
print()
nn10 = nn[-8:]
print("nn10:",nn10)

nn: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

nn1: [ 0  6 11 12]

nn2: [2 3 4 5 6 7 8]

nn3: [0 1 2 3 4 5]

nn4:  [0 3 6 9]

nn5 : [3 7]

nn6: [14 11  8  5]

nn7:  [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

nn8:  [0 1 2 3 4]

nn9: [ 4  7 10 13 16 19]

nn10: [13 14 15 16 17 18 19 20]


In [ ]:
CREATING ARRAYS AND SLICING VALUES OUT OF ARRAY(SPECIAL EXAMPLE)

In [ ]:
consider numpy array below

In [49]:
nnr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0],
                [6, 9, 100, 201.1]])
print("nnr:", nnr)

# now we are going to find our another numpy array from this array , see below

nnr: [[ -1.    2.    0.    4. ]
 [  4.   -0.5   6.    0. ]
 [  2.6   0.    7.    8. ]
 [  3.   -7.    4.    2. ]
 [  6.    9.  100.  201.1]]


In [55]:
arr =nnr[:3,::2]
print("arr:", arr)

arr: [[-1.   0. ]
 [ 4.   6. ]
 [ 2.6  7. ]]


In [51]:
arr1 = nnr[1:3,::2]
print("arr1:", arr1)

arr1: [[4.  6. ]
 [2.6 7. ]]


In [52]:
arr2 = nnr[0:4,::3]
print("arr2: ", arr2)

arr2:  [[-1.   4. ]
 [ 4.   0. ]
 [ 2.6  8. ]
 [ 3.   2. ]]


In [56]:
arr3 =nnr[:2,1:3]
print("arr3: ", arr3)

arr3:  [[ 2.   0. ]
 [-0.5  6. ]]


In [ ]:
CREATING NUMPY ARRAY HAVING 10 DIFFERENT VALUES FROM 1 TO 6 

In [58]:
s = np.linspace(1,6,10)
print("s: ", s)
print()
# Creating 8 different values from range 1 to 4
s1 = np.linspace(1,4,8)
print("s1: ", s1)

s:  [1.         1.55555556 2.11111111 2.66666667 3.22222222 3.77777778
 4.33333333 4.88888889 5.44444444 6.        ]

s1:  [1.         1.42857143 1.85714286 2.28571429 2.71428571 3.14285714
 3.57142857 4.        ]


In [61]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("x:", x)
print()
print("now we are creating 2*2*3") 
# it means 2 numpy array of shape (2,3)
print()
x11 =x.reshape(2,2,3)
print("x11:", x11)
print()
x12 = x.reshape(1,6,2)
print("x12:", x12)

x: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

now we are creating 2*2*3

x11: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

x12: [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]]


In [70]:
xx = np.array([[1,2,3,4,11,12],[5,6,7,8,13,14],[9,10,11,12,15,16]])
print("xx: ", xx)
print(xx.shape)
print()
xx1 = xx.reshape(2,3,3)
print("xx1:",xx1)
print(xx1.shape)
print()
xx2 = xx.reshape(3,3,2)
print("xx2: ", xx2)
print()
xxp =xx.flatten()
print("xxp: ", xxp)

xx:  [[ 1  2  3  4 11 12]
 [ 5  6  7  8 13 14]
 [ 9 10 11 12 15 16]]
(3, 6)

xx1: [[[ 1  2  3]
  [ 4 11 12]
  [ 5  6  7]]

 [[ 8 13 14]
  [ 9 10 11]
  [12 15 16]]]
(2, 3, 3)

xx2:  [[[ 1  2]
  [ 3  4]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]]

 [[ 9 10]
  [11 12]
  [15 16]]]

xxp:  [ 1  2  3  4 11 12  5  6  7  8 13 14  9 10 11 12 15 16]


In [69]:
arm = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("arm:", arm)
print("type(arm):", type(arm))
print("arm.dtype:", arm.dtype)
print()
arm1 = arm.flatten()
print("arm1: ", arm1)

arm: [[1 2 3]
 [4 5 6]
 [7 8 9]]
type(arm): <class 'numpy.ndarray'>
arm.dtype: int32

arm1:  [1 2 3 4 5 6 7 8 9]


In [ ]:
BASIC OPERATION IN NUMPY

In [95]:
n = np.array([1,2,3,4,5,6])
print("n: ", n)
print()
# PERFORMING SUM

n1 = n+4
print("n1: ", n1)
nn = n.sum()
print("nn: ", nn)
print()

# PERFORMING SUBTRACT
n2 = n-2
print("n2: ", n2)

# PERFORMING MULTIPLY

n3 = n*3
print("n3: ", n3)

# PERFORMING DIVIDE

n4 = n/2
print("n4: ", n4)

# PERFORMING POWER

n5 = n**2
print("n5:", n5)

n:  [1 2 3 4 5 6]

n1:  [ 5  6  7  8  9 10]
nn:  21

n2:  [-1  0  1  2  3  4]
n3:  [ 3  6  9 12 15 18]
n4:  [0.5 1.  1.5 2.  2.5 3. ]
n5: [ 1  4  9 16 25 36]


In [20]:
m1 = np.array([10,20])
m2 = np.array([30,40])
m3 = np.sum([m1,m2])
print("m3:", m3)
print()
m4 =np.sum([m1,m2], axis=1)
print("m4:", m4)
print()
m5 = np.sum([m1,m2], axis=0)
print("m5:", m5)

m3: 100

m4: [30 70]

m5: [40 60]


In [ ]:
TRANSPOSE FUNCTION ON NUMPY ARRAY

In [78]:
bb = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("bb: ", bb)
print()
print("TRANSPOSE_ARRAY: ", bb.T)

bb:  [[1 2 3]
 [4 5 6]
 [7 8 9]]

TRANSPOSE_ARRAY:  [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
CONSIDER NUMPY ARRAY OF SHAPE(3,3) FROM LIST

In [94]:
bb1 = np.array([[1,2,3],[11,12,13],[15,16,19]])
print("bb1:", bb1)
print()
print("bb1.shape:", bb1.shape)
print("type(bb1):", type(bb1))
print("bb1.dtype:", bb1.dtype)

# performing maximum function
bb2 = bb1.max()
print("bb2.max():", bb2)

# performing minimum
bb3 = bb1.min()
print("bb3:", bb3)

# Now max() value across rows(axis=1)each row
bb4 = bb1.max(axis=1)
print("bb4:", bb4)

# min() value across rows(axis=1)each row
bb5 = bb1.min(axis=1)
print("bb5:", bb5)

# again max value across vertical each column
bb6 = bb1.max(axis=0)
print("bb6:", bb6)

# again max value across vertical each column

bb7 = bb1.min(axis=0)
print("bb7:", bb7)
print()
print("sum function")

bb8 = bb1.sum()
print("bb8:", bb8)

bb1: [[ 1  2  3]
 [11 12 13]
 [15 16 19]]

bb1.shape: (3, 3)
type(bb1): <class 'numpy.ndarray'>
bb1.dtype: int32
bb2.max(): 19
bb3: 1
bb4: [ 3 13 19]
bb5: [ 1 11 15]
bb6: [15 16 19]
bb7: [1 2 3]

sum function
bb8: 92


In [2]:
import numpy as np

a = np.array([[1, 2],
            [3, 4]])
b=np.array([[4, 3],
             [2, 1]])

print("a+b:", a+b)
print()
print("a-b:", a-b)
print()
print("a.dot(b):", a.dot(b))

a+b: [[5 5]
 [5 5]]

a-b: [[-3 -1]
 [ 1  3]]

a.dot(b): [[ 8  5]
 [20 13]]


In [ ]:
MORE NUMPY ARRAY FUNCTION

In [22]:
a = np.array([2,8,3,4,25,36,49,128])
print("a:", a)
print()
b = np.sin(a)
print("b:", b)
print()
c = np.square(a)
print("c_square:", c)
print()
d = np.sqrt(a)
print("d_sqrt:", d)
print()
e=  np.exp(a)
print("e_exp: ", e)
print()
f = np.mean(a)
print("f:", f)
print()
g = np.median(a)
print("g:", g)
print()
k = np.std(a)
print("k:", k)

a: [  2   8   3   4  25  36  49 128]

b: [ 0.90929743  0.98935825  0.14112001 -0.7568025  -0.13235175 -0.99177885
 -0.95375265  0.72103771]

c_square: [    4    64     9    16   625  1296  2401 16384]

d_sqrt: [ 1.41421356  2.82842712  1.73205081  2.          5.          6.
  7.         11.3137085 ]

e_exp:  [7.38905610e+00 2.98095799e+03 2.00855369e+01 5.45981500e+01
 7.20048993e+10 4.31123155e+15 1.90734657e+21 3.88770841e+55]

f: 31.875

g: 16.5

k: 39.797730777017925


In [ ]:
SORTING OF NUMPY ARRAY

In [15]:
a = np.array([[1, 4, 2],
               [3, 4, 6],
               [0, -1, 5]])
print("a:", a)
print()
b1 = np.sort(a, axis=None)
print("b1:",b1)
print()


a: [[ 1  4  2]
 [ 3  4  6]
 [ 0 -1  5]]

b1: [-1  0  1  2  3  4  4  5  6]


In [ ]:
ROWWISE SORTING ARRAY

In [17]:
aa = np.array([[1, 4, 2],
               [3, 4, 6],
               [0, -1, 5]])
print("aa:", aa)
print()
bb = np.sort(aa,axis=1)
print("rowise sorting_bb:", bb)

aa: [[ 1  4  2]
 [ 3  4  6]
 [ 0 -1  5]]

rowise sorting_bb: [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]


In [ ]:
COLUMNWISE SORTING ARRAY

In [22]:
cc = np.array([[1, 4, 2],
               [3, 4, 6],
               [0, -1, 5]])
print("cc:", cc)
print()
dd = np.sort(cc,axis=0)
print(dd)

cc: [[ 1  4  2]
 [ 3  4  6]
 [ 0 -1  5]]

[[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [ ]:
IMPORTANT ONE

In [29]:
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),
          ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

arr = np.array(values, dtype = dtypes)
print("arr: ", arr)
print()
print("type(arr):", type(arr))
print()
abr = np.sort(arr,order='name')
print("abr:", abr)
print()
print("below It wll sort by year(ascending order")
print()
abr1 = np.sort(arr, order =['grad_year','cgpa'])
print("abr1: ", abr1)

arr:  [(b'Hrithik', 2009, 8.5) (b'Ajay', 2008, 8.7) (b'Pankaj', 2008, 7.9)
 (b'Aakash', 2009, 9. )]

type(arr): <class 'numpy.ndarray'>

abr: [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]

below It wll sort by year(ascending order

abr1:  [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


In [ ]:
STACKING

In [ ]:
Stacking: Several arrays can be stacked together along different axes.
np.vstack: To stack arrays along vertical axis.
np.hstack: To stack arrays along horizontal axis.
np.column_stack: To stack 1-D arrays as columns into 2-D arrays.
np.concatenate: To stack arrays along specified axis (axis is passed as argument)

In [37]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])
c = [5,6]

print("NOW PERFORMING VERTIAL STACK(V STACK)")
x = np.vstack((a,b))
print("x:", x)
print()
print("PERFORMING COLUMN STACK")
print()
x1 = np.hstack((a,b))
print("x1:", x1)

print("PERFORMING COLUMN STACK(A&C)") 
print()
x2 =  np.column_stack((a,c))
print("x2: ", x2)

print("PERFORMING COLUMN STACK(B&C)")
print()
x3 = np.column_stack((b,c))
print("x3:", x3)

print()
print("PERFORMING CONCATENATE()")
x4 = np.concatenate((a,b),1)
print("x4:", x4)

NOW PERFORMING VERTIAL STACK(V STACK)
x: [[1 2]
 [3 4]
 [5 6]
 [7 8]]

PERFORMING COLUMN STACK

x1: [[1 2 5 6]
 [3 4 7 8]]
PERFORMING COLUMN STACK(A&C)

x2:  [[1 2 5]
 [3 4 6]]
PERFORMING COLUMN STACK(B&C)

x3: [[5 6 5]
 [7 8 6]]

PERFORMING CONCATENATE()
x4: [[1 2 5 6]
 [3 4 7 8]]


In [11]:
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])
x1 = np.vstack((n1,n1))
print("x1:", x1)
print()
x2 = np.hstack((n1,n2))
print("x2:", x2)
print()
x3 = np.column_stack((n1,n2))
print("x3:", x3)

x1: [[10 20 30]
 [10 20 30]]

x2: [10 20 30 40 50 60]

x3: [[10 40]
 [20 50]
 [30 60]]


In [ ]:
NUMPY INTERSECTION & DIFFERENCE

In [16]:
n3 =np.array([10,20,30,40,50,60])
n4 = np.array([50,60,70,80,90])
print()
print("FINDING INTERSECTION BETWEEN 2 NUMPY ARRAY")
n5 = np.intersect1d(n3,n4)
print("n5:", n5)
print()
print("FINDING DIFFERENCE")
print("here we have find values which are there in n3 only")
n6 = np.setdiff1d(n3,n4)
print("n6:", n6)
print()
n7 = np.setdiff1d(n4,n3)
print("n7: ", n7)


FINDING INTERSECTION BETWEEN 2 NUMPY ARRAY
n5: [50 60]

FINDING DIFFERENCE
here we have find values which are there in n3 only
n6: [10 20 30 40]

n7:  [70 80 90]


In [ ]:
NUMPY SAVE AND LOAD

In [26]:
c1 =np.array([10,20,30,40,50,60,70,80])
print("c1:", c1)
np.save("my_numpy", c1)
print()
c2 = np.load("my_numpy.npy")
print("c2:", c2)

c1: [10 20 30 40 50 60 70 80]
c2: [10 20 30 40 50 60 70 80]


In [ ]:
SPLITTING NUMPY ARRAY

In [ ]:
Splitting:For splitting, we have these functions:
np.hsplit: Split array along horizontal axis.
np.vsplit: Split array along vertical axis.
np.array_split: Split array along specified axis.

In [49]:
a = np.array([[1, 3, 5, 7, 9, 11],
               [2, 4, 6, 8, 10, 12]])
print("a:",a)
print()
print("type(a):", type(a))
print()
print("a.shape:", a.shape)
print()
print("PERFORMING HSPLIT()")
print()
u = np.hsplit(a,2)
print("u:", u)
print()
u1 = np.hsplit(a,3)
print("u1:", u1)
print()
u2 = np.vsplit(a,2)
print("u2:", u2)
print()

a: [[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]]

type(a): <class 'numpy.ndarray'>

a.shape: (2, 6)

PERFORMING HSPLIT()

u: [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]

u1: [array([[1, 3],
       [2, 4]]), array([[5, 7],
       [6, 8]]), array([[ 9, 11],
       [10, 12]])]

u2: [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]



In [ ]:
MORE EXAMPLES

In [53]:
a = np.array([1.0, 2.0, 3.0])
c = [2.0, 2.0, 2.0]

x =a*c
print("x:", x)

x: [2. 4. 6.]


In [ ]:
ADVANCED INDEXING

In [60]:
rr = np.array([[2, 3],[5, 6],[8, 9]])
print("rr:", rr)
print()
print("now we are slicing this numpy array")
print()
c = rr[[0,1,2],[0,1,0]]
# first index value[0,1,2] telling the position of [2,3],[5,6],[8,9] and second index value[0,1,0] telling position
# of value in output we have
print("c;", c)
print()
d = rr[[0,1],[0,0]]
print("d:", d)

print()

arr2 = np.array(((2, 3, 4),(9, 8, 7),(1, 2, 3)))
print("arr2:", arr2)
print()
print("now performing slicing")
print()
arr22 = arr2[[0,1,2],[0,2,2]]
print("arr22:", arr22)

print()
file = open("context24.txt", "w")
file.write(str(arr22)

rr: [[2 3]
 [5 6]
 [8 9]]

now we are slicing this numpy array

c; [2 6 8]

d: [2 5]

arr2: [[2 3 4]
 [9 8 7]
 [1 2 3]]

now performing slicing

arr22: [2 7 3]



TypeError: write() argument must be str, not numpy.ndarray