In [1]:
import numpy

In [2]:
from numpy import *

In [3]:
arr1 = array([
               [1,2,3],
               [4,5,6]
])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [15]:
array1 = array([[1,2,3,4],[5,6,7,8]])
print(array1)
print(array1.dtype)
print(array1.shape)
print(array1.size)
print(array1.flatten())
print(array1.ndim)
array2 = array1.reshape(4,2)
print(array2)
# print(array1.ndim)its a two dimensional array


[[1 2 3 4]
 [5 6 7 8]]
int32
(2, 4)
8
[1 2 3 4 5 6 7 8]
2
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
array1 = array([[1,2,3,6,2,9],[4,5,6,7,5,3]])
arr3 = array1.reshape(3,4)
print(arr3)
print()
arr3 = array1.reshape(4,3)
print(arr3)

[[1 2 3 6]
 [2 9 4 5]
 [6 7 5 3]]

[[1 2 3]
 [6 2 9]
 [4 5 6]
 [7 5 3]]


In [21]:
array1 = array([[1,2,3,6,2,9],[4,5,6,7,5,3]])
arr3 =  array1.reshape(2,2,3)
print(arr3)

[[[1 2 3]
  [6 2 9]]

 [[4 5 6]
  [7 5 3]]]


In [ ]:
MATRICES

In [38]:
arr4= array([[1,2,3,4],[5,6,7,8]])
print(arr4)
# NOW WE ARE CONVERTING IT INTO MATRIX(to perform more operation)
m = matrix(arr4)
print(m)
print(type(m))
m1 = matrix('1 2 3 4 ; 5 6 7 8')
print(m1)
m2 = matrix('4 5;6 7;11 12; 13 15')
print(m2)
print()
m3 = matrix('11 12 13;14 15 16;17 18 19')
print("m3",m3)
print()
m4 = matrix('20 21 22; 23 24 25; 26 27 28')
print("m4",m4)
print()
print(diagonal(m3))
print()
print(m3.max())
print(m3.min())
print()
m5 = m3*m4;
print(m5)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.matrix'>
[[1 2 3 4]
 [5 6 7 8]]
[[ 4  5]
 [ 6  7]
 [11 12]
 [13 15]]

m3 [[11 12 13]
 [14 15 16]
 [17 18 19]]

m4 [[20 21 22]
 [23 24 25]
 [26 27 28]]

[11 15 19]

19
11

[[ 834  870  906]
 [1041 1086 1131]
 [1248 1302 1356]]
